import React from "react";
import { Edit3, Eye, ZoomIn, ZoomOut, RotateCcw } from "lucide-react";
import { cn } from "@/lib/utils";
import { SOPPreview } from "@/components/sop/preview/SOPPreview";
import { SOPHeader, Activity } from "@/types/sop";
import { Button } from "@/components/ui/button";

interface LivePreviewProps {
  viewMode: "edit" | "preview";
  setViewMode: (mode: "edit" | "preview") => void;
  scale: number;
  zoom: number;
  setZoom: React.Dispatch<React.SetStateAction<number>>;
  header: SOPHeader;
  activities: Activity[];
  roles: string[];
  isHydrated: boolean;
  expandedActivities: string[];
}

export function LivePreview({
  viewMode,
  setViewMode,
  scale,
  zoom,
  setZoom,
  header,
  activities,
  roles,
  isHydrated,
  expandedActivities,
}: LivePreviewProps) {
  const handleZoomIn = () => setZoom((prev) => Math.min(prev + 0.1, 2));
  const handleZoomOut = () => setZoom((prev) => Math.max(prev - 0.1, 0.5));
  const handleResetZoom = () => setZoom(1);
  return (
    <section
      className={cn(
        "flex-1 overflow-y-auto custom-scrollbar print:p-0 print:bg-white transition-all duration-500 h-full [scrollbar-gutter:stable] print:flex print:visible bg-dot-grid-subtle",
        viewMode === "preview"
          ? "bg-card flex"
          : "bg-card hidden lg:flex",
      )}
    >
      <div className="min-h-full w-full p-4 md:py-8 md:px-4 flex flex-col items-center print:p-0 print:m-0">
        <div className="w-full max-w-[1000px] mb-4 flex items-center justify-between print:hidden">
          <div className="hidden md:flex items-center bg-muted p-0.5 rounded-lg">
            <button
              onClick={() => setViewMode("edit")}
              className={cn(
                "px-2.5 py-1 rounded-md text-xs font-medium transition-all flex items-center gap-1.5",
                viewMode === "edit"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-slate-500 dark:text-slate-400 hover:text-foreground",
              )}
            >
              <Edit3 className="w-3.5 h-3.5" />
              <span>Editor</span>
            </button>
            <button
              onClick={() => setViewMode("preview")}
              className={cn(
                "px-2.5 py-1 rounded-md text-xs font-medium transition-all flex items-center gap-1.5",
                viewMode === "preview"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-slate-500 dark:text-slate-400 hover:text-foreground",
              )}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Preview</span>
            </button>
          </div>
          <div className="flex items-center">
            <div className="flex items-center bg-background border border-border rounded-lg p-0.5 shadow-sm">
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6 rounded-md text-muted-foreground hover:text-foreground"
                onClick={handleZoomOut}
                aria-label="Zoom Out"
              >
                <ZoomOut className="w-3 h-3" />
              </Button>
              <div className="px-1.5 min-w-[36px] text-center">
                <span className="text-[10px] font-semibold text-foreground">
                  {Math.round(zoom * 100)}%
                </span>
              </div>
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6 rounded-md text-muted-foreground hover:text-foreground"
                onClick={handleZoomIn}
                aria-label="Zoom In"
              >
                <ZoomIn className="w-3 h-3" />
              </Button>
              <div className="w-px h-4 bg-border mx-0.5" />
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6 rounded-md text-muted-foreground hover:text-foreground"
                onClick={handleResetZoom}
                aria-label="Reset Zoom"
              >
                <RotateCcw className="w-3 h-3" />
              </Button>
            </div>
          </div>
        </div>

        <div
          className="w-full flex justify-center transition-all duration-500 print-unscale print:m-0 print:block"
          style={{
            transform: `scale(${scale})`,
            transformOrigin: "top center",
            marginBottom: `calc(297mm * ${scale - 1})`,
          }}
        >
          <SOPPreview
            header={header}
            activities={activities}
            roles={roles}
            isHydrated={isHydrated}
            expandedActivities={expandedActivities}
          />
        </div>

        <footer className="mt-16 text-muted-foreground/50 text-[8px] font-medium tracking-wider uppercase pb-8 print:hidden leading-none">
          Generated by Digital SOP Builder System &bull; 2026
        </footer>
      </div>
    </section>
  );
}
