import React from "react";
import { ChevronRight, ZoomIn, ZoomOut, RotateCcw } from "lucide-react";
import { cn } from "@/lib/utils";
import { SOPPreview } from "@/components/sop/preview/SOPPreview";
import { SOPHeader, Activity } from "@/types/sop";
import { Button } from "@/components/ui/button";

interface LivePreviewProps {
  viewMode: "edit" | "preview";
  scale: number;
  zoom: number;
  setZoom: React.Dispatch<React.SetStateAction<number>>;
  header: SOPHeader;
  activities: Activity[];
  roles: string[];
  isHydrated: boolean;
  expandedActivities: string[];
}

export function LivePreview({
  viewMode,
  scale,
  zoom,
  setZoom,
  header,
  activities,
  roles,
  isHydrated,
  expandedActivities,
}: LivePreviewProps) {
  const handleZoomIn = () => setZoom((prev) => Math.min(prev + 0.1, 2));
  const handleZoomOut = () => setZoom((prev) => Math.max(prev - 0.1, 0.5));
  const handleResetZoom = () => setZoom(1);
  return (
    <section
      className={cn(
        "flex-1 bg-[#F1F5F9] overflow-y-auto custom-scrollbar print:p-0 print:bg-white transition-all duration-500 h-full [scrollbar-gutter:stable] print:flex print:visible",
        viewMode === "preview"
          ? "bg-white flex"
          : "bg-slate-100 hidden lg:flex",
      )}
    >
      <div className="min-h-full w-full p-4 md:py-12 md:px-6 flex flex-col items-center print:p-0 print:m-0">
        <div className="w-full max-w-[1000px] mb-4 md:mb-8 flex items-center justify-between print:hidden">
          <div className="hidden md:flex items-center gap-2 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] leading-none">
            <span>KEMENAG</span>
            <ChevronRight className="w-3 h-3" />
            <span>SOP BUILDER</span>
            <ChevronRight className="w-3 h-3" />
            <span className="text-emerald-600">LIVE PREVIEW</span>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center bg-white border border-slate-200 rounded-full p-1 shadow-sm">
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 rounded-full text-slate-500 hover:text-emerald-600 hover:bg-emerald-50"
                onClick={handleZoomOut}
                title="Zoom Out"
              >
                <ZoomOut className="w-3.5 h-3.5" />
              </Button>
              <div className="px-2 min-w-[45px] text-center border-x border-slate-100">
                <span className="text-[10px] font-black text-slate-600">
                  {Math.round(zoom * 100)}%
                </span>
              </div>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 rounded-full text-slate-500 hover:text-emerald-600 hover:bg-emerald-50"
                onClick={handleZoomIn}
                title="Zoom In"
              >
                <ZoomIn className="w-3.5 h-3.5" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="ml-1 h-7 w-7 rounded-full text-slate-400 hover:text-slate-600 hover:bg-slate-100"
                onClick={handleResetZoom}
                title="Reset Zoom"
              >
                <RotateCcw className="w-3.5 h-3.5" />
              </Button>
            </div>
            <div className="bg-emerald-50 text-emerald-600 border border-emerald-100 px-3 py-1 rounded-full text-[9px] font-black animate-pulse">
              SYNCING ACTIVE
            </div>
          </div>
        </div>

        <div
          className="w-full flex justify-center transition-all duration-500 print-unscale print:m-0 print:block"
          style={{
            transform: `scale(${scale})`,
            transformOrigin: "top center",
            marginBottom: `calc(297mm * ${scale - 1})`,
          }}
        >
          <SOPPreview
            header={header}
            activities={activities}
            roles={roles}
            isHydrated={isHydrated}
            expandedActivities={expandedActivities}
          />
        </div>

        <footer className="mt-20 text-slate-400 text-[9px] font-black tracking-[0.3em] uppercase pb-12 print:hidden leading-none">
          Generated by Digital SOP Builder System &bull; 2026
        </footer>
      </div>
    </section>
  );
}
